version: "3.7"
services:

    web:
      build: .
      volumes: 
        - ./logs:/app/logs
        - /etc/localtime:/etc/localtime:ro
      environment:
        TZ: Europe/Moscow
      # ports: "5000:5000"
      user: 1000:1000
      restart: always

networks:
  default:
    ipam:
      config:
        - subnet: 172.191.111.0/16